services:

  application:
    image: ghcr.io/grobolof/laravel:php-8.5-fpm-trixie
    env_file: .env
    working_dir: ${APP_PATH}
    environment:
      PHP_IDE_CONFIG: serverName=${APP_HOST}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
    volumes:
      - ./:${APP_PATH}
